// Flattens a saved Building Markup into the list of things an estimator would price.
//
// Pure — no Salesforce, no network, no I/O. That is the point: the mapping can be judged
// against real markups offline (scripts/dry-run-line-items.ts) long before anything is allowed
// to write to a Quote.
//
// An earlier version also held planLines()/ProposedLine/quantityFor(), which priced each layer
// as quantity × $1 according to a per-asset-type unit. The sheet under the markup image
// supersedes all of that: pricing is now internal m² and external m² against per-row rates,
// finalised in Salesforce. Keeping a second pricing model here would guarantee the two
// disagreed. What remains is the flattener and the join keys.

import { MIN_POINTS, measureShape } from "@/lib/kml/standard-markup/measure";
import { lotPlanFromId } from "@/lib/kml/standard-markup/parcels/parcel-id";
import type { BuildingMarkupFile, SavedMarkupShape } from "@/lib/maps/building-markup-file";
import type { MarkupLayer } from "./types";

/**
 * A stable key for a shape that has no persisted id.
 *
 * Save files written before shape ids were persisted (version 1) have nothing to join on, and
 * the in-memory id is regenerated by replaceAll() on every open — so without this, reopening a
 * markup and re-syncing would duplicate every shape's line item.
 *
 * A content fingerprint over the geometry, so it is identical across a save/reopen and CHANGES
 * when the shape is edited. That second property is deliberate rather than unfortunate: an
 * edited shape is a different quantity, and quoting it as an update to the old line would hide
 * the change. Same reasoning as the KMZ Analyser's fingerprinted segment_id.
 *
 * Not cryptographic and doesn't need to be — FNV-1a over a canonical string, and a collision
 * would need two shapes with identical rounded geometry, which is the same shape.
 */
function fingerprintShape(shape: SavedMarkupShape): string {
  const canonical = [
    shape.mode,
    shape.widthMetres.toFixed(1),
    ...shape.points.map((p) => `${p.lat.toFixed(6)},${p.lng.toFixed(6)}`),
  ].join("|");
  let hash = 0x811c9dc5;
  for (let i = 0; i < canonical.length; i++) {
    hash ^= canonical.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return `fp${hash.toString(16).padStart(8, "0")}`;
}

/** The layer keys, exported so the UI and the planner can never disagree about them — they
 *  are the join key a re-sync matches on, so a second definition somewhere would silently
 *  start creating duplicate line items. */
export const SUBJECT_KEY = "subject";
export const lotKey = (id: string) => `lot:${id}`;
export const shapeKey = (shape: SavedMarkupShape) => `shape:${shape.id ?? fingerprintShape(shape)}`;

/** Flattens a save file into the list of things that could be priced, in the order an
 *  operator reads them: the site, then the detected lots, then the drawn shapes. */
export function layersFrom(file: BuildingMarkupFile): MarkupLayer[] {
  const layers: MarkupLayer[] = [];

  // ── The subject property ────────────────────────────────────────────────────────
  // areaSqm and lotPlan are optional on the file: they exist in the resolver but were
  // dropped on one line before this feature (resolve.ts returned only subject.ring), so a
  // markup saved before that change has a boundary and no figure. Null, not zero — a
  // missing measurement must read as missing.
  //
  // Its address is the one the operator TYPED, which beats anything the address layer could
  // return: a corner lot has several valid frontages, and this is the one the job is under.
  layers.push({
    key: SUBJECT_KEY,
    kind: "subject",
    label: "Site",
    areaSqm: file.subjectAreaSqm ?? null,
    lengthMetres: null,
    widthMetres: null,
    lotPlan: file.subjectLotPlan ?? null,
    street: file.address.street || null,
    suburb: file.address.suburb || null,
    mode: null,
    color: "red",
    included: !file.hideSubject,
    points: file.subjectRing,
  });

  // ── Detected adjoining lots ─────────────────────────────────────────────────────
  const excluded = new Set(file.excludedIds);
  for (const lot of file.neighbours) {
    layers.push({
      key: lotKey(lot.id),
      kind: "lot",
      label: "Lot",
      areaSqm: lot.areaSqm,
      lengthMetres: null,
      widthMetres: null,
      // The cadastre id IS the lot/plan for every state that has one (lotplan / lotidstring
      // / parcel_spi), with a `#2` suffix only where two parcels collided. Not every id is
      // one, though — see parcel-id.ts.
      lotPlan: lotPlanFromId(lot.id),
      street: lot.street ?? null,
      // Falls back to the job's suburb: an adjoining lot is in the same suburb in all but
      // pathological cases, and it saves retyping it on every row.
      suburb: lot.suburb ?? file.address.suburb ?? null,
      mode: null,
      color: "blue",
      included: !excluded.has(lot.id),
      points: lot.ring,
    });
  }

  // ── Hand-drawn shapes ───────────────────────────────────────────────────────────
  for (const shape of file.shapes) {
    const measured = measureShape(shape);
    layers.push({
      key: shapeKey(shape),
      kind: "shape",
      label: "Shape",
      areaSqm: measured.areaSqm > 0 ? Math.round(measured.areaSqm) : null,
      lengthMetres: measured.lengthMetres === null ? null : Math.round(measured.lengthMetres),
      widthMetres: shape.mode === "line" ? shape.widthMetres : null,
      lotPlan: null,
      // No parcel, so no address layer to ask. The suburb is inherited; the street is left for
      // the operator, because a shape over a kerb belongs to whichever road it runs along and
      // nothing in the file knows which that is.
      street: null,
      suburb: file.address.suburb || null,
      mode: shape.mode,
      color: shape.color,
      included: shape.points.length >= MIN_POINTS[shape.mode],
      points: shape.points,
    });
  }

  return layers;
}
