/**
 * Local government area -> state, from the ABS ASGS 2021 LGA list (geo.abs.gov.au, LGA_NAME_2021).
 * Generated once, not fetched at run time: the list changes at council amalgamations, a
 * handful of times a decade, and a stale entry only costs a blank state on a card.
 *
 * Names keep ABS spelling with the "(NSW)"/"(Vic.)" disambiguators stripped, so a name used
 * in two states (Bayside, Central Coast, Flinders, Latrobe…) maps to both and the caller has
 * to settle it some other way.
 */
export const LGA_STATES: Record<string, readonly string[]> = {
  // Renamed after the 2021 list was cut (Moreland -> Merri-bek, 2022).
  "Merri-bek": ["VIC"],
  "Adelaide": ["SA"],
  "Adelaide Hills": ["SA"],
  "Adelaide Plains": ["SA"],
  "Albany": ["WA"],
  "Albury": ["NSW"],
  "Alexandrina": ["SA"],
  "Alice Springs": ["NT"],
  "Alpine": ["VIC"],
  "Anangu Pitjantjatjara Yunkunytjatjara": ["SA"],
  "Ararat": ["VIC"],
  "Armadale": ["WA"],
  "Armidale Regional": ["NSW"],
  "Ashburton": ["WA"],
  "Augusta Margaret River": ["WA"],
  "Aurukun": ["QLD"],
  "Ballarat": ["VIC"],
  "Ballina": ["NSW"],
  "Balonne": ["QLD"],
  "Balranald": ["NSW"],
  "Banana": ["QLD"],
  "Banyule": ["VIC"],
  "Barcaldine": ["QLD"],
  "Barcoo": ["QLD"],
  "Barkly": ["NT"],
  "Barossa": ["SA"],
  "Barunga West": ["SA"],
  "Bass Coast": ["VIC"],
  "Bassendean": ["WA"],
  "Bathurst Regional": ["NSW"],
  "Baw Baw": ["VIC"],
  "Bayside": ["NSW", "VIC"],
  "Bayswater": ["WA"],
  "Bega Valley": ["NSW"],
  "Bellingen": ["NSW"],
  "Belmont": ["WA"],
  "Belyuen": ["NT"],
  "Benalla": ["VIC"],
  "Berri Barmera": ["SA"],
  "Berrigan": ["NSW"],
  "Beverley": ["WA"],
  "Blackall Tambo": ["QLD"],
  "Blacktown": ["NSW"],
  "Bland": ["NSW"],
  "Blayney": ["NSW"],
  "Blue Mountains": ["NSW"],
  "Boddington": ["WA"],
  "Bogan": ["NSW"],
  "Boroondara": ["VIC"],
  "Boulia": ["QLD"],
  "Bourke": ["NSW"],
  "Boyup Brook": ["WA"],
  "Break O'Day": ["TAS"],
  "Brewarrina": ["NSW"],
  "Bridgetown-Greenbushes": ["WA"],
  "Brighton": ["TAS"],
  "Brimbank": ["VIC"],
  "Brisbane": ["QLD"],
  "Broken Hill": ["NSW"],
  "Brookton": ["WA"],
  "Broome": ["WA"],
  "Broomehill-Tambellup": ["WA"],
  "Bruce Rock": ["WA"],
  "Bulloo": ["QLD"],
  "Buloke": ["VIC"],
  "Bunbury": ["WA"],
  "Bundaberg": ["QLD"],
  "Burdekin": ["QLD"],
  "Burke": ["QLD"],
  "Burnie": ["TAS"],
  "Burnside": ["SA"],
  "Burwood": ["NSW"],
  "Busselton": ["WA"],
  "Byron": ["NSW"],
  "Cabonne": ["NSW"],
  "Cairns": ["QLD"],
  "Cambridge": ["WA"],
  "Camden": ["NSW"],
  "Campaspe": ["VIC"],
  "Campbelltown": ["NSW", "SA"],
  "Canada Bay": ["NSW"],
  "Canning": ["WA"],
  "Canterbury-Bankstown": ["NSW"],
  "Capel": ["WA"],
  "Cardinia": ["VIC"],
  "Carnamah": ["WA"],
  "Carnarvon": ["WA"],
  "Carpentaria": ["QLD"],
  "Carrathool": ["NSW"],
  "Casey": ["VIC"],
  "Cassowary Coast": ["QLD"],
  "Ceduna": ["SA"],
  "Central Coast": ["NSW", "TAS"],
  "Central Darling": ["NSW"],
  "Central Desert": ["NT"],
  "Central Goldfields": ["VIC"],
  "Central Highlands": ["QLD", "TAS"],
  "Cessnock": ["NSW"],
  "Chapman Valley": ["WA"],
  "Charles Sturt": ["SA"],
  "Charters Towers": ["QLD"],
  "Cherbourg": ["QLD"],
  "Chittering": ["WA"],
  "Circular Head": ["TAS"],
  "Clare and Gilbert Valleys": ["SA"],
  "Claremont": ["WA"],
  "Clarence": ["TAS"],
  "Clarence Valley": ["NSW"],
  "Cleve": ["SA"],
  "Cloncurry": ["QLD"],
  "Cobar": ["NSW"],
  "Cockburn": ["WA"],
  "Coffs Harbour": ["NSW"],
  "Colac Otway": ["VIC"],
  "Collie": ["WA"],
  "Coober Pedy": ["SA"],
  "Cook": ["QLD"],
  "Coolamon": ["NSW"],
  "Coolgardie": ["WA"],
  "Coomalie ": ["NT"],
  "Coonamble": ["NSW"],
  "Coorong": ["SA"],
  "Coorow": ["WA"],
  "Cootamundra-Gundagai Regional": ["NSW"],
  "Copper Coast": ["SA"],
  "Corangamite": ["VIC"],
  "Corrigin": ["WA"],
  "Cottesloe ": ["WA"],
  "Cowra": ["NSW"],
  "Cranbrook": ["WA"],
  "Croydon": ["QLD"],
  "Cuballing": ["WA"],
  "Cue": ["WA"],
  "Cumberland": ["NSW"],
  "Cunderdin": ["WA"],
  "Dalwallinu": ["WA"],
  "Dandaragan": ["WA"],
  "Dardanup": ["WA"],
  "Darebin": ["VIC"],
  "Darwin": ["NT"],
  "Darwin Waterfront Precinct": ["NT"],
  "Denmark": ["WA"],
  "Derby-West Kimberley": ["WA"],
  "Derwent Valley": ["TAS"],
  "Devonport": ["TAS"],
  "Diamantina": ["QLD"],
  "Donnybrook-Balingup": ["WA"],
  "Doomadgee": ["QLD"],
  "Dorset": ["TAS"],
  "Douglas": ["QLD"],
  "Dowerin": ["WA"],
  "Dubbo Regional": ["NSW"],
  "Dumbleyung": ["WA"],
  "Dundas": ["WA"],
  "Dungog": ["NSW"],
  "East Arnhem": ["NT"],
  "East Fremantle": ["WA"],
  "East Gippsland": ["VIC"],
  "East Pilbara": ["WA"],
  "Edward River": ["NSW"],
  "Elliston": ["SA"],
  "Esperance": ["WA"],
  "Etheridge": ["QLD"],
  "Eurobodalla": ["NSW"],
  "Exmouth": ["WA"],
  "Fairfield": ["NSW"],
  "Federation": ["NSW"],
  "Flinders": ["QLD", "TAS"],
  "Flinders Ranges": ["SA"],
  "Forbes": ["NSW"],
  "Franklin Harbour": ["SA"],
  "Frankston": ["VIC"],
  "Fraser Coast": ["QLD"],
  "Fremantle": ["WA"],
  "Gannawarra": ["VIC"],
  "Gawler": ["SA"],
  "George Town": ["TAS"],
  "Georges River": ["NSW"],
  "Gilgandra": ["NSW"],
  "Gingin": ["WA"],
  "Gladstone": ["QLD"],
  "Glamorgan-Spring Bay": ["TAS"],
  "Glen Eira": ["VIC"],
  "Glen Innes Severn": ["NSW"],
  "Glenelg": ["VIC"],
  "Glenorchy": ["TAS"],
  "Gnowangerup": ["WA"],
  "Gold Coast": ["QLD"],
  "Golden Plains": ["VIC"],
  "Goomalling": ["WA"],
  "Goondiwindi": ["QLD"],
  "Gosnells": ["WA"],
  "Goulburn Mulwaree": ["NSW"],
  "Goyder": ["SA"],
  "Grant": ["SA"],
  "Greater Bendigo": ["VIC"],
  "Greater Dandenong": ["VIC"],
  "Greater Geelong": ["VIC"],
  "Greater Geraldton": ["WA"],
  "Greater Hume Shire": ["NSW"],
  "Greater Shepparton": ["VIC"],
  "Griffith": ["NSW"],
  "Gunnedah": ["NSW"],
  "Gwydir": ["NSW"],
  "Gympie": ["QLD"],
  "Halls Creek": ["WA"],
  "Harvey": ["WA"],
  "Hawkesbury": ["NSW"],
  "Hay": ["NSW"],
  "Hepburn": ["VIC"],
  "Hilltops": ["NSW"],
  "Hinchinbrook": ["QLD"],
  "Hindmarsh": ["VIC"],
  "Hobart": ["TAS"],
  "Hobsons Bay": ["VIC"],
  "Holdfast Bay": ["SA"],
  "Hope Vale": ["QLD"],
  "Hornsby": ["NSW"],
  "Horsham": ["VIC"],
  "Hume": ["VIC"],
  "Hunters Hill": ["NSW"],
  "Huon Valley": ["TAS"],
  "Indigo": ["VIC"],
  "Inner West": ["NSW"],
  "Inverell": ["NSW"],
  "Ipswich": ["QLD"],
  "Irwin": ["WA"],
  "Isaac": ["QLD"],
  "Jerramungup": ["WA"],
  "Joondalup": ["WA"],
  "Junee": ["NSW"],
  "Kalamunda": ["WA"],
  "Kalgoorlie-Boulder": ["WA"],
  "Kangaroo Island": ["SA"],
  "Karoonda East Murray": ["SA"],
  "Karratha": ["WA"],
  "Katanning": ["WA"],
  "Katherine": ["NT"],
  "Kellerberrin": ["WA"],
  "Kempsey": ["NSW"],
  "Kent": ["WA"],
  "Kentish": ["TAS"],
  "Kiama": ["NSW"],
  "Kimba": ["SA"],
  "King Island": ["TAS"],
  "Kingborough": ["TAS"],
  "Kingston": ["SA", "VIC"],
  "Knox": ["VIC"],
  "Kojonup": ["WA"],
  "Kondinin": ["WA"],
  "Koorda": ["WA"],
  "Kowanyama": ["QLD"],
  "Ku-ring-gai": ["NSW"],
  "Kulin": ["WA"],
  "Kwinana": ["WA"],
  "Kyogle": ["NSW"],
  "Lachlan": ["NSW"],
  "Lake Grace": ["WA"],
  "Lake Macquarie": ["NSW"],
  "Lane Cove": ["NSW"],
  "Latrobe": ["TAS", "VIC"],
  "Launceston": ["TAS"],
  "Laverton": ["WA"],
  "Leeton": ["NSW"],
  "Leonora": ["WA"],
  "Light": ["SA"],
  "Lismore": ["NSW"],
  "Litchfield": ["NT"],
  "Lithgow": ["NSW"],
  "Liverpool": ["NSW"],
  "Liverpool Plains": ["NSW"],
  "Livingstone": ["QLD"],
  "Lockhart": ["NSW"],
  "Lockhart River": ["QLD"],
  "Lockyer Valley": ["QLD"],
  "Loddon": ["VIC"],
  "Logan": ["QLD"],
  "Longreach": ["QLD"],
  "Lower Eyre Peninsula": ["SA"],
  "Loxton Waikerie": ["SA"],
  "MacDonnell": ["NT"],
  "Macedon Ranges": ["VIC"],
  "Mackay": ["QLD"],
  "Maitland": ["NSW"],
  "Mandurah": ["WA"],
  "Manjimup": ["WA"],
  "Manningham": ["VIC"],
  "Mansfield": ["VIC"],
  "Mapoon": ["QLD"],
  "Maralinga Tjarutja": ["SA"],
  "Maranoa": ["QLD"],
  "Mareeba": ["QLD"],
  "Maribyrnong": ["VIC"],
  "Marion": ["SA"],
  "Maroondah": ["VIC"],
  "McKinlay": ["QLD"],
  "Meander Valley": ["TAS"],
  "Meekatharra": ["WA"],
  "Melbourne": ["VIC"],
  "Melton": ["VIC"],
  "Melville": ["WA"],
  "Menzies": ["WA"],
  "Merredin": ["WA"],
  "Mid Murray": ["SA"],
  "Mid-Coast": ["NSW"],
  "Mid-Western Regional": ["NSW"],
  "Mildura": ["VIC"],
  "Mingenew": ["WA"],
  "Mitcham": ["SA"],
  "Mitchell": ["VIC"],
  "Moira": ["VIC"],
  "Monash": ["VIC"],
  "Moonee Valley": ["VIC"],
  "Moora": ["WA"],
  "Moorabool": ["VIC"],
  "Morawa": ["WA"],
  "Moree Plains": ["NSW"],
  "Moreland": ["VIC"],
  "Moreton Bay": ["QLD"],
  "Mornington": ["QLD"],
  "Mornington Peninsula": ["VIC"],
  "Mosman": ["NSW"],
  "Mosman Park": ["WA"],
  "Mount Alexander": ["VIC"],
  "Mount Barker": ["SA"],
  "Mount Gambier": ["SA"],
  "Mount Isa": ["QLD"],
  "Mount Magnet": ["WA"],
  "Mount Marshall": ["WA"],
  "Mount Remarkable": ["SA"],
  "Moyne": ["VIC"],
  "Mukinbudin": ["WA"],
  "Mundaring": ["WA"],
  "Murchison": ["WA"],
  "Murray": ["WA"],
  "Murray Bridge": ["SA"],
  "Murray River": ["NSW"],
  "Murrindindi": ["VIC"],
  "Murrumbidgee": ["NSW"],
  "Murweh": ["QLD"],
  "Muswellbrook": ["NSW"],
  "Nambucca Valley": ["NSW"],
  "Nannup": ["WA"],
  "Napranum": ["QLD"],
  "Naracoorte Lucindale": ["SA"],
  "Narembeen": ["WA"],
  "Narrabri": ["NSW"],
  "Narrandera": ["NSW"],
  "Narrogin": ["WA"],
  "Narromine": ["NSW"],
  "Nedlands": ["WA"],
  "Newcastle": ["NSW"],
  "Ngaanyatjarraku": ["WA"],
  "Nillumbik": ["VIC"],
  "Noosa": ["QLD"],
  "North Burnett": ["QLD"],
  "North Sydney": ["NSW"],
  "Northam": ["WA"],
  "Northampton": ["WA"],
  "Northern Areas": ["SA"],
  "Northern Beaches": ["NSW"],
  "Northern Grampians": ["VIC"],
  "Northern Midlands": ["TAS"],
  "Northern Peninsula Area": ["QLD"],
  "Norwood Payneham and St Peters": ["SA"],
  "Nungarin": ["WA"],
  "Oberon": ["NSW"],
  "Onkaparinga": ["SA"],
  "Orange": ["NSW"],
  "Orroroo Carrieton": ["SA"],
  "Palm Island": ["QLD"],
  "Palmerston": ["NT"],
  "Parkes": ["NSW"],
  "Paroo": ["QLD"],
  "Parramatta": ["NSW"],
  "Penrith": ["NSW"],
  "Peppermint Grove": ["WA"],
  "Perenjori": ["WA"],
  "Perth": ["WA"],
  "Peterborough": ["SA"],
  "Pingelly": ["WA"],
  "Plantagenet": ["WA"],
  "Playford": ["SA"],
  "Pormpuraaw": ["QLD"],
  "Port Adelaide Enfield": ["SA"],
  "Port Augusta": ["SA"],
  "Port Hedland": ["WA"],
  "Port Lincoln": ["SA"],
  "Port Macquarie-Hastings": ["NSW"],
  "Port Phillip": ["VIC"],
  "Port Pirie": ["SA"],
  "Port Stephens": ["NSW"],
  "Prospect": ["SA"],
  "Pyrenees": ["VIC"],
  "Quairading": ["WA"],
  "Queanbeyan-Palerang Regional": ["NSW"],
  "Queenscliffe": ["VIC"],
  "Quilpie": ["QLD"],
  "Randwick": ["NSW"],
  "Ravensthorpe": ["WA"],
  "Redland": ["QLD"],
  "Renmark Paringa": ["SA"],
  "Richmond": ["QLD"],
  "Richmond Valley": ["NSW"],
  "Robe": ["SA"],
  "Rockhampton": ["QLD"],
  "Rockingham": ["WA"],
  "Roper Gulf": ["NT"],
  "Roxby Downs": ["SA"],
  "Ryde": ["NSW"],
  "Salisbury": ["SA"],
  "Sandstone": ["WA"],
  "Scenic Rim": ["QLD"],
  "Serpentine-Jarrahdale": ["WA"],
  "Shark Bay": ["WA"],
  "Shellharbour": ["NSW"],
  "Shoalhaven": ["NSW"],
  "Singleton": ["NSW"],
  "Snowy Monaro Regional": ["NSW"],
  "Snowy Valleys": ["NSW"],
  "Somerset": ["QLD"],
  "Sorell": ["TAS"],
  "South Burnett": ["QLD"],
  "South Gippsland": ["VIC"],
  "South Perth": ["WA"],
  "Southern Downs": ["QLD"],
  "Southern Grampians": ["VIC"],
  "Southern Mallee": ["SA"],
  "Southern Midlands": ["TAS"],
  "Stirling": ["WA"],
  "Stonnington": ["VIC"],
  "Strathbogie": ["VIC"],
  "Strathfield": ["NSW"],
  "Streaky Bay": ["SA"],
  "Subiaco": ["WA"],
  "Sunshine Coast": ["QLD"],
  "Surf Coast": ["VIC"],
  "Sutherland Shire": ["NSW"],
  "Swan": ["WA"],
  "Swan Hill": ["VIC"],
  "Sydney": ["NSW"],
  "Tablelands": ["QLD"],
  "Tammin": ["WA"],
  "Tamworth Regional": ["NSW"],
  "Tasman": ["TAS"],
  "Tatiara": ["SA"],
  "Tea Tree Gully": ["SA"],
  "Temora": ["NSW"],
  "Tenterfield": ["NSW"],
  "The Hills Shire": ["NSW"],
  "Three Springs": ["WA"],
  "Tiwi Islands": ["NT"],
  "Toodyay": ["WA"],
  "Toowoomba": ["QLD"],
  "Torres": ["QLD"],
  "Torres Strait Island": ["QLD"],
  "Townsville": ["QLD"],
  "Towong": ["VIC"],
  "Trayning": ["WA"],
  "Tumby Bay": ["SA"],
  "Tweed": ["NSW"],
  "Unley": ["SA"],
  "Upper Gascoyne": ["WA"],
  "Upper Hunter Shire": ["NSW"],
  "Upper Lachlan Shire": ["NSW"],
  "Uralla": ["NSW"],
  "Victor Harbor": ["SA"],
  "Victoria Daly": ["NT"],
  "Victoria Park": ["WA"],
  "Victoria Plains": ["WA"],
  "Vincent": ["WA"],
  "Wagait": ["NT"],
  "Wagga Wagga": ["NSW"],
  "Wagin": ["WA"],
  "Wakefield": ["SA"],
  "Walcha": ["NSW"],
  "Walgett": ["NSW"],
  "Walkerville": ["SA"],
  "Wandering": ["WA"],
  "Wangaratta": ["VIC"],
  "Wanneroo": ["WA"],
  "Waratah-Wynyard": ["TAS"],
  "Waroona": ["WA"],
  "Warren": ["NSW"],
  "Warrnambool": ["VIC"],
  "Warrumbungle Shire": ["NSW"],
  "Wattle Range": ["SA"],
  "Waverley": ["NSW"],
  "Weddin": ["NSW"],
  "Weipa": ["QLD"],
  "Wellington": ["VIC"],
  "Wentworth": ["NSW"],
  "West Arnhem": ["NT"],
  "West Arthur": ["WA"],
  "West Coast": ["TAS"],
  "West Daly": ["NT"],
  "West Tamar": ["TAS"],
  "West Torrens": ["SA"],
  "West Wimmera": ["VIC"],
  "Western Downs": ["QLD"],
  "Westonia": ["WA"],
  "Whitehorse": ["VIC"],
  "Whitsunday": ["QLD"],
  "Whittlesea": ["VIC"],
  "Whyalla": ["SA"],
  "Wickepin": ["WA"],
  "Williams": ["WA"],
  "Willoughby": ["NSW"],
  "Wiluna": ["WA"],
  "Wingecarribee": ["NSW"],
  "Winton": ["QLD"],
  "Wodonga": ["VIC"],
  "Wollondilly": ["NSW"],
  "Wollongong": ["NSW"],
  "Wongan-Ballidu": ["WA"],
  "Woodanilling": ["WA"],
  "Woollahra": ["NSW"],
  "Woorabinda": ["QLD"],
  "Wudinna": ["SA"],
  "Wujal Wujal": ["QLD"],
  "Wyalkatchem": ["WA"],
  "Wyndham": ["VIC"],
  "Wyndham-East Kimberley": ["WA"],
  "Yalgoo": ["WA"],
  "Yankalilla": ["SA"],
  "Yarra": ["VIC"],
  "Yarra Ranges": ["VIC"],
  "Yarrabah": ["QLD"],
  "Yarriambiack": ["VIC"],
  "Yass Valley": ["NSW"],
  "Yilgarn": ["WA"],
  "York": ["WA"],
  "Yorke Peninsula": ["SA"],
};
